/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

/**
 *
 * @author User
 */
public class menuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form menuAdmin
     */
    public menuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnAddVenue = new javax.swing.JButton();
        btnDeleteVenue = new javax.swing.JButton();
        btnBookedVenue = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(289, 322));
        setSize(new java.awt.Dimension(256, 289));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, -1));

        btnAddUser.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, -1));

        btnDeleteUser.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnDeleteUser.setText("Delete User");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, -1));

        btnAddVenue.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnAddVenue.setText("Add Venue");
        btnAddVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVenueActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 220, -1));

        btnDeleteVenue.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnDeleteVenue.setText("Delete Venue");
        btnDeleteVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVenueActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, -1));

        btnBookedVenue.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnBookedVenue.setText("View Booked Venue");
        btnBookedVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookedVenueActionPerformed(evt);
            }
        });
        getContentPane().add(btnBookedVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 220, -1));

        jPanel1.setBackground(new java.awt.Color(43, 199, 236));
        jPanel1.setForeground(new java.awt.Color(73, 88, 120));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        addUser frm = new addUser(this, rootPaneCheckingEnabled);
        frm.show();
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        deleteUser frm = new deleteUser(this, rootPaneCheckingEnabled);
        frm.show();
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnAddVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVenueActionPerformed
        addVenue frm = new addVenue(this, rootPaneCheckingEnabled);
        frm.show();
    }//GEN-LAST:event_btnAddVenueActionPerformed

    private void btnDeleteVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVenueActionPerformed
        deleteVenue frm = new deleteVenue(this, rootPaneCheckingEnabled);
        frm.show();
    }//GEN-LAST:event_btnDeleteVenueActionPerformed

    private void btnBookedVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookedVenueActionPerformed
        bookedVenue frm = new bookedVenue(this, rootPaneCheckingEnabled);
        frm.show();
    }//GEN-LAST:event_btnBookedVenueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnAddVenue;
    private javax.swing.JButton btnBookedVenue;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnDeleteVenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
