/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.event.ItemEvent;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Booking;
import model.TextFileRW;
import model.Venue;

/**
 *
 * @author User
 */
public class bookVenue extends javax.swing.JDialog {

    TextFileRW t = new TextFileRW();
    /**
     * Creates new form bookVenue
     */
    public bookVenue(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ArrayList<Booking> bookings = t.readAllBooking(LocalDate.now().toString());
        ArrayList<Venue> venues = t.readAllVenue();
        
        for(int i=0; i<7;i++){
            ddlDate.addItem(LocalDate.now().plusDays(i+1).toString());
        }
        
        for(int i=0; i<venues.size();i++){
            ddlVenue.addItem(String.format("%s - %s", venues.get(i).getCode(),venues.get(i).getName()));
        }
        ResetView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ddlVenue = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ddlDate = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSchedule = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(433, 348));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ddlVenue.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ddlVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });
        getContentPane().add(ddlVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Venue :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        ddlDate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ddlDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });
        getContentPane().add(ddlDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 170, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Date :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        tbSchedule.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tbSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"9.00 am", "Booked by S0001"},
                {"10.00 am", "-"},
                {"11.00 am", "Booked by S0001"},
                {"12.00 am", "Booked by S0001"},
                {"1.00 am", "Booked by S0001"},
                {"2.00 am", "-"},
                {"3.00 am", "-"},
                {"4.00 am", null}
            },
            new String [] {
                "Time", "Availability"
            }
        ));
        tbSchedule.setEnabled(false);
        tbSchedule.setRowHeight(20);
        tbSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbScheduleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSchedule);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 350, 200));

        jPanel1.setBackground(new java.awt.Color(43, 199, 236));
        jPanel1.setForeground(new java.awt.Color(73, 88, 120));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbScheduleMouseClicked
        int row = evt.getY() / tbSchedule.getRowHeight(); //get the row of the button
        
        if (row < tbSchedule.getRowCount() && row >= 0) {
            String date = ddlDate.getSelectedItem().toString();
            String venue = ddlVenue.getSelectedItem().toString();
            String time = tbSchedule.getValueAt(row, 0).toString();
            String avaibility = tbSchedule.getValueAt(row, 1).toString();
            
            if(avaibility.equals("-")){
                if(JOptionPane.showConfirmDialog(rootPane, String.format("Do you wan to book on %s, %s",date, time)) == JOptionPane.OK_OPTION){
                    new TextFileRW().bookVenue(new Booking(venue, menuLecturer.lecturerID, date, row));
                    JOptionPane.showMessageDialog(this, "Booked", "N/A", JOptionPane.INFORMATION_MESSAGE);
                }
                ResetView();
            }
            else
                JOptionPane.showMessageDialog(this, "Not Available", "N/A", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tbScheduleMouseClicked

    private void ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed
        int date = ddlDate.getSelectedIndex();
        int venue = ddlVenue.getSelectedIndex();
        if(date > -1 && venue > -1)
            ResetView();
    }//GEN-LAST:event_ActionPerformed

    private void ResetView(){
        String[][] data = new String[8][2];
        String[] header = {"Time", "Availability"};
        String venue = ddlVenue.getSelectedItem().toString();
        String date = ddlDate.getSelectedItem().toString();

        data[0][0] = "09.00 am";
        data[1][0] = "10.00 am";
        data[2][0] = "11.00 am";
        data[3][0] = "12.00 pm";
        data[4][0] = "01.00 pm";
        data[5][0] = "02.00 pm";
        data[6][0] = "03.00 pm";
        data[7][0] = "04.00 pm";

        for(int i=0;i<8;i++)
            data[i][1] = "-";
        ArrayList<Booking> bookings = t.readAllBooking(date);

        for(int i=0;i<bookings.size();i++){
            Booking b = bookings.get(i);
            if(date.equals(b.getDate()) && venue.equals(b.getVenueID()))
                data[b.getTime()][1] = String.format("Booked by %s", b.getLecturerID());
        }

        tbSchedule.setModel(
                new javax.swing.table.DefaultTableModel(data, header)
        );
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                bookVenue dialog = new bookVenue(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ddlDate;
    private javax.swing.JComboBox<String> ddlVenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSchedule;
    // End of variables declaration//GEN-END:variables
}
